.Dd July 23, 2015
.Dt CONVERT2DA 1
.Os
.Sh NAME
.Nm convert2da
.Nd BioWare 2DA/GDA to 2DA/CSV converter
.Sh SYNOPSIS
.Nm convert2da
.Op Ar options
.Ar
.Sh DESCRIPTION
.Nm
converts BioWare's 2DA and GDA files into (cleanly formatted)
ASCII 2DA or CSV files.
2DA files are two-dimensional arrays, or tables, holding various
information and used throughout many of the BioWare games.
They can come in two flavors: binary and plain-text ASCII.
GDA files are conceptually the same, but they
store their data inside a GFF, a binary hierarchical format.
Unlike 2DA files, a GDA does not store its column header name
directory.
Instead, only a CRC hash of the name encoded in
little-endian UTF-16 is stored.
.Pp
This tool can read all of those formats and produces an easily
readable, cleanly formatted ASCII 2DA.
Alternatively, it can create a CSV file for further processing.
It also contains a lookup table to convert GDA column header hashes
back to readable names.
Not all column header names are known, though.
.Sh OPTIONS
.Bl -tag -width xxxx -compact
.It Fl h
.It Fl Fl help
Show a help text and exit.
.It Fl Fl version
Show version information and exit.
.It Fl o Ar file
.It Fl Fl output Ar file
Write the output to this file.
If this option is not used, the output is written to
.Dv stdout .
.It Fl a
.It Fl Fl 2da
Convert the 2DA or GDA file into an ASCII 2DA file.
This is the default mode of operation.
.It Fl b
.It Fl Fl 2dab
Convert the 2DA or GDA file into a binary 2DA file.
.It Fl c
.It Fl Fl csv
Convert the 2DA or GDA file into an CSV file.
.El
.Bl -tag -width xx -compact
.It Ar file
The name of the 2DA or GDA file to read.
.Pp
If more than one input file is given, they must all be GDA files
and use the same column layout. They will be pasted together and
converted as one GDA. This mimics how the M2DA (multiple 2DA/GDA)
work in the
.Em Dragon Age
games.
.El
.Sh EXAMPLES
Convert the 2DA file1.2da into an ASCII 2DA
.Pa file2.2da :
.Pp
.Dl $ convert2da -a file1.2da -o file2.2da
.Pp
Convert the 2DA file1.2da into an ASCII 2DA on
.Dv stdout :
.Pp
.Dl $ convert2da -a file1.2da
.Pp
Convert the 2DA
.Pa file1.2da
into a binary 2DA
.Pa file2.2da :
.Pp
.Dl $ convert2da -b file1.2da -o file2.2da
.Pp
Convert the 2DA
.Pa file1.2da
into a CSV file:
.Pp
.Dl $ convert2da -c file1.2da -o file2.csv
.Sh SEE ALSO
.Xr gff2xml 1
.Pp
More information about the xoreos project can be found on
.Lk https://xoreos.org/ "its website"
.Ns .
.Sh AUTHORS
This program is part of the xoreos-tools package, which in turn is
part of the xoreos project, and was written by the xoreos team.
Please see the
.Pa AUTHORS
file for details.
