.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac

.TH nbfs2tga 1 2015-07-23 "xoreos-tools"
.SH NAME
nbfs2tga - Nintendo raw NBFS image to TGA converter
.SH SYNOPSIS
nbfs2tga [<options>] <nbfs> <nbfp> <tga> [<width>] [<height>]
.SH DESCRIPTION
.PP
.B nbfs2tga
converts Nintendo's raw NBFS images into common TGA images. Both
an NBFS file, containing the pixel data, and an NBFP file with
the palette data are needed. If no height is specified, it is
calculated using the width value and the size of the NBFS file.
If no width is specified either, this tool tries to guess the
dimensions. It might guess the wrong dimensions.
.PP
.SH OPTIONS
.TP 4
.B -h
.PD 0
.TP 4
.B --help
.PD
Show a help text and exit.
.TP 4
.B --version
Show version information and exit.
.TP 4
<nbfs>
The name of the NBFS file to read. The NBFS contains the pixel
graphics part of the image.
.TP 4
<nbfp>
The name of the NBFP file to use. The NBFP file contains the palette
part of the image.
.TP 4
<tga>
The resulting TGA file will be written there.
.TP 4
[<width>]
The width of the NBFS image.
.TP 4
[<height>]
The height of the NBFS image.
.SH "SEE ALSO"
More information about the xoreos project can be found on
.URL "https://xoreos.org/" "its website" .
.SH AUTHORS
This program is part of the xoreos-tools package, which in turn is
part of the xoreos project, and was written by the xoreos team.
Please see the AUTHORS file for details.
