.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac

.TH ncsdis 1 2015-10-08 "xoreos-tools"
.SH NAME
ncsdis - BioWare NWScript bytecode disassembler
.SH SYNOPSIS
ncsdis [<options>] <input file> [<output file>]
.SH DESCRIPTION
.PP
.B ncsdis
disassembles NCS files, compiled bytecode of the NWScript scripting
language used by every single Aurora engine game, except for the
Nintendo DS game
.IR "Sonic Chronicles: The Dark Brotherhood" .
The output, while not as clear as the C-like source code that produced
the bytecode, is human-readable.
.PP
ncsdis is meant as a better maintainable and more complete replacement
of the disassembly mode found in the OpenKnights nwnnsscomp tool.
As such, it fixes provides these enhancements:
.PD 0
.IP - 2
Compilable in 64-bit mode
.IP - 2
Out of the box support for all Aurora engine games
.IP - 2
Support for array opcodes added in
.I "Dragon Age: Origins"
.IP - 2
Support for reference opcodes added in
.I "Dragon Age II"
.IP - 2
Knowledge of additional variable types
.IP - 2
No need to provide an external nwscript.nss file
.PD
.PP
Additionally, ncsdis can create a dot file specifying a control flow
graph of the disassembly. It can be plotted into a graph by the dot
tool of the GraphViz suite.
.BR WARNING :
these graphs can get very large very quickly. To keep the resulting
image small, set a small font and font size when calling GraphViz,
and decrease the nodesep and ranksep values.
.PP
Since there is no way to automatically detect for which game this
script is, this information must be provided on the command. If
no game is specified, the ACTION opcode that call an engine function,
such as "GetModule" or trigonometry functions, will only display a
number instead of a function name.
.SH OPTIONS
.TP 4
.B -h
.PD 0
.TP 4
.B --help
.PD
Show a help text and exit.
.TP 4
.B --version
Show version information and exit.
.TP 4
.B --list
Create a full disassembly listing, including byte addresses and the
raw bytecode, similar to the disassembly mode of nwnnsscomp. This
is the default mode.
.TP 4
.B --assembly
Only create the human-readable mnemonics part of the disassembly
listing. Useful for modifying and extending the script.
.TP 4
.B --dot
Create a flow control graph in the dot language, to be plotted by
the GraphViz suite.
.TP 4
.B --nwn
Use engine function tables of the game
.IR "Neverwinter Nights" .
.TP 4
.B --nwn2
Use engine function tables of the game
.IR "Neverwinter Nights 2" .
.TP 4
.B --kotor
Use engine function tables of the game
.IR "Star Wars: Knights of the Old Republic" .
.TP 4
.B --kotor2
Use engine function tables of the game
.IR "Star Wars: Knights of the Old Republic II - The Sith Lords" .
.TP 4
.B --jade
Use engine function tables of the game
.IR "Jade Empire" .
.TP 4
.B --witcher
Use engine function tables of the game
.IR "The Witcher" .
.TP 4
.B --dragonage
Use engine function tables of the game
.IR "Dragon Age: Origins" .
.TP 4
.B --dragonage2
Use engine function tables of the game
.IR "Dragon Age II" .
.TP 4
<input file>
The NCS file to disassemble.
.TP 4
[<output file>]
The disassembly will be written there. If no output file is specified,
the disassembly will be written to stdout.
.SH EXAMPLES
.ad l
.B Disassemble the script file.ncs:
.nf
.ad l
ncsdis file.ncs file.lst
.PP
.fi
.ad l
.B Disassemble the script file.ncs and write the listing to stdout:
.nf
.ad l
ncsdis file.ncs
.PP
.fi
.ad l
.B Disassemble the Jade Empire script file.ncs:
.nf
.ad l
ncsdis --jade file.ncs file.list
.PP
.fi
.ad l
.B Disassemble the Jade Empire script file.ncs in pure disassembly mode:
.nf
.ad l
ncsdis --assembly --jade file.ncs file.asm
.PP
.fi
.ad l
.B Create a dot graph file of the Neverwinter Nights script file.ncs:
.nf
.ad l
ncsdis --dot --nwn file.ncs file.dot
.PP
.fi
.ad l
.B Create a dot graph file of the Neverwinter Nights script file.ncs and plot it:
.nf
.ad l
ncsdis --dot --nwn file.ncs | dot -Gnodesep=0.1 -Granksep=0.1 -Gfontname="Courier New" -Nfontname="Courier New" -Gfontsize=10 -Nfontsize=8 -Earrowsize=0.5 -Tpng > file.png
.PP
.fi
.ad b
.SH "SEE ALSO"
.BR nwnnsscomp(1),
.BR dot (1)
.PP
More information about the xoreos project can be found on
.URL "https://xoreos.org/" "its website" .
.SH AUTHORS
This program is part of the xoreos-tools package, which in turn is
part of the xoreos project, and was written by the xoreos team.
Please see the AUTHORS file for details.
