.Dd July 23, 2015
.Dt UNNDS 1
.Os
.Sh NAME
.Nm unnds
.Nd Nintendo DS archive extractor
.Sh SYNOPSIS
.Nm unnds
.Op Ar options
.Ar command
.Ar file
.Sh DESCRIPTION
.Nm
extract Nintendo DS ROMs.
Only the resource files are extracted, not the executable binaries.
.Sh OPTIONS
.Bl -tag -width xxxx -compact
.It Fl h
.It Fl Fl help
Show a help text and exit.
.It Fl Fl version
Show version information and exit.
.El
.Bl -tag -width xx -compact
.It Ar command
.Bl -tag -width xx -compact
.It Cm i
Display meta-information about the archive
.It Cm l
List archive contents
.It Cm e
Extract files to current directory
.El
.It Ar file
The NDS archive to read.
.El
.Sh EXAMPLES
View meta-information of the archive
.Pa archive.nds :
.Pp
.Dl $ unnds i archive.nds
.Pp
List all files contained in the archive
.Pa archive.nds :
.Pp
.Dl $ unnds l archive.nds
.Pp
Extract all files from the archive
.Pa archive.nds :
.Pp
.Dl $ unnds e archive.nds
.Sh SEE ALSO
More information about the xoreos project can be found on
.Lk https://xoreos.org/ "its website"
.Ns .
.Sh AUTHORS
This program is part of the xoreos-tools package, which in turn is
part of the xoreos project, and was written by the xoreos team.
Please see the
.Pa AUTHORS
file for details.
