.Dd September 27, 2018
.Dt UNTWS 1
.Os
.Sh NAME
.Nm untws
.Nd CD Projekt Red TheWitcherSave archive extractor
.Sh SYNOPSIS
.Nm untws
.Ar command
.Ar archive
.Op Ar
.Sh DESCRIPTION
.Nm
extracts CD Projekt Red TheWitcherSave archives, found in The Witcher.
.Pp
TheWitcherSave files are custom archives that contain both files and the name of the area.
.Sh OPTIONS
.Bl -tag -width xxxx -compact
.It Ar command
.Bl -tag -width xx -compact
.It Cm l
List filesystem contents
.It Cm e
Extract files to current directory, stripping directories
.El
.It Ar archive
The TheWitcherSave archive to extract
.It Ar file
One or more files to extract.
If none are given, the whole archive is extracted.
.El
.Sh EXAMPLES
List all files contained in the archive
.Pa archive.thewitchersave :
.Pp
.Dl $ untws l archive.thewitchersave
.Pp
Extract all files from the archive
.Pa archive.thewitchersave :
.Pp
.Dl $ untws e archive.thewitchersave
.Sh SEE ALSO
.Xr tws 1 ,
.Xr unerf 1 ,
.Xr unrim 1
.Pp
More information about the xoreos project can be found on
.Lk https://xoreos.org/ "its website"
.Ns .
.Sh AUTHORS
This program is part of the xoreos-tools package, which in turn is
part of the xoreos project, and was written by the xoreos team.
Please see the
.Pa AUTHORS
file for details.
